# the theme we use
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# this is the main title visible in the left side bar and in the browser title
title: AWS Testing
# this is the description from the meta tags
description: This is a guide on testing AWS services and in general about testing in AWS Cloud.
# the base URL/domain
url: https://aws-testing.ideapool.community

content:
  samples: https://github.com/Idea-Pool/aws-testing/tree/main/samples

permalink: pretty

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md

# these are the information boxes can be used in the documents
# e.g.
# {: .more }
# some more information
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  more:
    title: More information
    color: grey-dk
  questions:
    title: Assess Your Understanding
    color: green

back_to_top: true
back_to_top_text: Back to top

footer_content: Copyright &copy; 2022- Idea Pool Community.
  Distributed by an <a href="https://github.com/idea-pool/aws-testing/tree/main/LICENSE" target="_blank">MIT license.</a>
  Idea Pool <a href="https://github.com/idea-pool" target="_blank">@GitHub</a>,
  <a href="http://ideapool.community" target="_blank">@WeAreCommunity</a>.
  <br>This site is <strong>under development</strong>.

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# logo: "/assets/images/idea-pool.png"

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

mermaid:
  version: "9.1.6"

heading_anchors: true

aux_links:
  AWS Testing on GitHub:
    - https://github.com/Idea-Pool/aws-testing

aux_links_new_tab: true

nav_external_links:
  - title: Contribution Guideline
    url: https://github.com/Idea-Pool/aws-testing/blob/main/CONTRIBUTING.md
#   - title: Idea Pool@GitHub
#     url: https://github.com/idea-pool
#   - title: Idea Pool@WeAreCommunity
#     url: http://ideapool.community

gh_edit_link: true
gh_edit_link_text: Help us improve this page with your contribution
gh_edit_repository: https://github.com/Idea-Pool/aws-testing
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: tree

ga_tracking: GTM-MN2TZZV
ga_tracking_anonymize_ip: true

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
